# Generated by Django 5.2 on 2026-02-26 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animateurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeEmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('icone', models.CharField(default='🎙️', max_length=10)),
                ('couleur', models.CharField(default='green', max_length=20)),
            ],
            options={
                'verbose_name': "Type d'émission",
                'verbose_name_plural': "Types d'émissions",
            },
        ),
        migrations.CreateModel(
            name='Emission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('fichier_audio', models.FileField(upload_to='emissions/audio/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='emissions/images/')),
                ('langue', models.CharField(choices=[('wolof', 'Wolof'), ('francais', 'Français'), ('arabe', 'Arabe'), ('wolof_fr', 'Wolof / Français')], default='wolof', max_length=20)),
                ('date_diffusion', models.DateField()),
                ('duree', models.CharField(blank=True, max_length=20)),
                ('nb_ecoutes', models.PositiveIntegerField(default=0)),
                ('publie', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='animateurs.animateur')),
                ('type_emission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='emissions.typeemission')),
            ],
            options={
                'verbose_name': 'Émission',
                'verbose_name_plural': 'Émissions',
                'ordering': ['-date_diffusion'],
            },
        ),
    ]
