# Generated by Django 5.2 on 2026-02-26 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Don',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_donateur', models.CharField(blank=True, default='Anonyme', max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('montant', models.DecimalField(decimal_places=0, max_digits=10)),
                ('methode', models.CharField(choices=[('wave', 'Wave'), ('orange_money', 'Orange Money'), ('free_money', 'Free Money'), ('carte', 'Carte bancaire')], max_length=20)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('recu', 'Reçu'), ('echec', 'Échec')], default='en_attente', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Don',
                'verbose_name_plural': 'Dons',
                'ordering': ['-created_at'],
            },
        ),
    ]
