# Generated by Django 5.2 on 2026-02-26 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('emission_principale', models.CharField(blank=True, max_length=200)),
                ('biographie', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='animateurs/')),
                ('actif', models.BooleanField(default=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Animateur',
                'verbose_name_plural': 'Animateurs',
                'ordering': ['ordre', 'nom'],
            },
        ),
    ]
