# Generated by Django 5.2 on 2026-02-26 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('categorie', models.CharField(choices=[('islam', 'Islam'), ('savoir', 'Savoir'), ('communaute', 'Communauté'), ('senegal', 'Sénégal'), ('monde', 'Monde')], max_length=20)),
                ('contenu', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='actualites/')),
                ('publie', models.BooleanField(default=True)),
                ('en_une', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Actualité',
                'verbose_name_plural': 'Actualités',
                'ordering': ['-created_at'],
            },
        ),
    ]
